# Default values for {{ cookiecutter.project_slug }}.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # repository will be built by your Makefile/Dockerfile
  repository: "{{ cookiecutter.project_slug }}-{{ cookiecutter.language }}"
  tag: "local"
  pullPolicy: IfNotPresent

service:
  grpcPort: 50051
  httpPort: 8080

swagger:
  enabled: {% if cookiecutter.enableSwagger == "y" %}true{% else %}false{% endif %}
  port: 8080
  file: service.swagger.json

probes:
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    initialDelaySeconds: 15
    periodSeconds: 20

